import type { Unit } from './types'

/** ~50 common vegetables. nameLocal is Marathi, shown alongside English everywhere. */
export const SEED_ITEMS: Array<[string, string, Unit]> = [
  ['Tomato', 'टोमॅटो', 'kg'],
  ['Onion', 'कांदा', 'kg'],
  ['Potato', 'बटाटा', 'kg'],
  ['Green Chilli', 'हिरवी मिरची', 'kg'],
  ['Coriander', 'कोथिंबीर', 'bundle'],
  ['Lemon', 'लिंबू', 'dozen'],
  ['Ginger', 'आले', 'kg'],
  ['Garlic', 'लसूण', 'kg'],
  ['Cauliflower', 'फ्लॉवर', 'piece'],
  ['Cabbage', 'कोबी', 'kg'],
  ['Brinjal', 'वांगी', 'kg'],
  ['Lady Finger', 'भेंडी', 'kg'],
  ['Bottle Gourd', 'दुधी भोपळा', 'kg'],
  ['Ridge Gourd', 'दोडका', 'kg'],
  ['Bitter Gourd', 'कारले', 'kg'],
  ['Snake Gourd', 'पडवळ', 'kg'],
  ['Ash Gourd', 'कोहळा', 'kg'],
  ['Pumpkin', 'लाल भोपळा', 'kg'],
  ['Cucumber', 'काकडी', 'kg'],
  ['Carrot', 'गाजर', 'kg'],
  ['Beetroot', 'बीट', 'kg'],
  ['Radish', 'मुळा', 'kg'],
  ['Turnip', 'सलगम', 'kg'],
  ['Capsicum', 'ढोबळी मिरची', 'kg'],
  ['French Beans', 'फरसबी', 'kg'],
  ['Cluster Beans', 'गवार', 'kg'],
  ['Flat Beans', 'वालपापडी', 'kg'],
  ['Cowpea Beans', 'चवळी शेंग', 'kg'],
  ['Green Peas', 'मटार', 'kg'],
  ['Ivy Gourd', 'तोंडली', 'kg'],
  ['Drumstick', 'शेवगा', 'kg'],
  ['Sweet Corn', 'मका', 'piece'],
  ['Baby Corn', 'बेबी कॉर्न', 'kg'],
  ['Spinach', 'पालक', 'bundle'],
  ['Fenugreek Leaves', 'मेथी', 'bundle'],
  ['Amaranth Leaves', 'माठ', 'bundle'],
  ['Dill Leaves', 'शेपू', 'bundle'],
  ['Colocasia Leaves', 'अळू', 'bundle'],
  ['Mint', 'पुदिना', 'bundle'],
  ['Curry Leaves', 'कढीपत्ता', 'bundle'],
  ['Spring Onion', 'कांदापात', 'bundle'],
  ['Green Garlic', 'लसूण पात', 'bundle'],
  ['Sweet Potato', 'रताळे', 'kg'],
  ['Yam', 'सुरण', 'kg'],
  ['Colocasia Root', 'अरबी', 'kg'],
  ['Raw Banana', 'कच्ची केळी', 'dozen'],
  ['Coconut', 'नारळ', 'piece'],
  ['Mushroom', 'अळंबी', 'piece'],
  ['Broccoli', 'ब्रोकोली', 'piece'],
  ['Zucchini', 'झुकिनी', 'kg'],
]
